#!/usr/bin/env bash
# Render a terminal scene from a VHS tape into scenes/NN.mp4. Run with TUT_SLUG set.
#   ./render-tape.sh 02 path/to/scene.tape
# The big upgrade over the sibling skill: terminal scenes are declarative .tape
# files (perfect typing, deterministic, re-renderable in seconds), not recordings.
# See references/terminal-vhs.md for tape authoring.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

NN="$(printf '%02d' "$((10#${1:?scene number required}))")"
SRC="${2:?tape file required}"

command -v vhs >/dev/null || die "vhs not installed (brew install vhs). Run preflight.sh."
[ -f "$SRC" ] || die "tape file not found: $SRC"

mkdir -p "$HDIR/tapes" "$HDIR/scenes"
OUT="$HDIR/scenes/${NN}.mp4"
TAPE="$HDIR/tapes/${NN}.tape"

# Normalize the tape: force 1920x1080 sizing and a single Output line pointing at
# scenes/NN.mp4, so every terminal scene concatenates cleanly. User Set lines for
# FontSize/Theme/TypingSpeed/Padding are preserved; Width/Height/Output are ours.
{
  echo "# Generated by render-tape.sh from $(basename "$SRC"). Do not edit; edit the source tape."
  echo "Output ${OUT}"
  grep -viE '^[[:space:]]*Output[[:space:]]' "$SRC" \
    | grep -viE '^[[:space:]]*Set[[:space:]]+Width[[:space:]]' \
    | grep -viE '^[[:space:]]*Set[[:space:]]+Height[[:space:]]' \
    | { echo "Set Width ${RES%x*}"; echo "Set Height ${RES#*x}"; cat; }
} > "$TAPE"

vhs "$TAPE"
[ -f "$OUT" ] || die "vhs did not produce $OUT (see the tape at $TAPE)"
echo "terminal scene $NN -> $OUT"
