#!/usr/bin/env bash
# Render a terminal scene from a VHS tape into scenes/NN.mp4. Run with TUT_SLUG set.
#   ./render-tape.sh 02 path/to/scene.tape
# The big upgrade over the sibling skill: terminal scenes are declarative .tape
# files (perfect typing, deterministic, re-renderable in seconds), not recordings.
# See references/terminal-vhs.md for tape authoring.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

NN="$(printf '%02d' "$((10#${1:?scene number required}))")"
SRC="${2:?tape file required}"

command -v vhs >/dev/null || die "vhs not installed (brew install vhs). Run preflight.sh."
[ -f "$SRC" ] || die "tape file not found: $SRC"

# Resolve the source tape to an absolute path before we cd (it may be relative
# to the original working directory).
SRC_ABS="$(cd "$(dirname "$SRC")" && pwd)/$(basename "$SRC")"

mkdir -p "$HDIR/tapes" "$HDIR/scenes"
HDIR_ABS="$(cd "$HDIR" && pwd)"      # for messaging
OUT_ABS="$HDIR_ABS/scenes/${NN}.mp4"

# VHS's parser rejects an absolute Output path (the leading slash), so we run vhs
# from inside the build dir and use RELATIVE tape + Output paths. This keeps the
# skill working even when TUT_BUILD_DIR is an absolute path.
cd "$HDIR"
TAPE_REL="tapes/${NN}.tape"
OUT_REL="scenes/${NN}.mp4"

# Normalize the tape: force 1920x1080 sizing and a single Output line pointing at
# scenes/NN.mp4, so every terminal scene concatenates cleanly. User Set lines for
# FontSize/Theme/TypingSpeed/Padding are preserved; Width/Height/Output are ours.
{
  echo "# Generated by render-tape.sh from $(basename "$SRC_ABS"). Do not edit; edit the source tape."
  echo "Output ${OUT_REL}"
  grep -viE '^[[:space:]]*Output[[:space:]]' "$SRC_ABS" \
    | grep -viE '^[[:space:]]*Set[[:space:]]+Width[[:space:]]' \
    | grep -viE '^[[:space:]]*Set[[:space:]]+Height[[:space:]]' \
    | { echo "Set Width ${RES%x*}"; echo "Set Height ${RES#*x}"; cat; }
} > "$TAPE_REL"

vhs "$TAPE_REL"
[ -f "$OUT_REL" ] || die "vhs did not produce $OUT_ABS (see the tape at $HDIR_ABS/$TAPE_REL)"
echo "terminal scene $NN -> $OUT_ABS"
